### ISSUE TITLE
catalog#map view should show the application name in the page title

### ISSUE THREAD

**Issue by ebenenglish** [projectblacklight/blacklight-maps#80]
Need to change the translation file `config/locales/blacklight-maps.en.yml` to include the application name in the page title for catalog#map view, like so:

```YAML
en:
  blacklight:
    maps:
      title: 'Map - %{application_name}'
```
